### ISSUE TITLE
Add Tables to AWS DB

### ISSUE THREAD

**Issue by brandonwardell20** [Tycodra/API_Playground#1]
I have created an AWS RDS MySQL database. Please add the tables to the DB by using a database manage to link to it. 

Endpoint: awecidian-db-instance-1.c70ko622aykj.us-east-2.rds.amazonaws.com
Port: 3306
Username: awecidian

**Comment by brandonwardell20** [comment]
I don't have the DB set up yet, but I am working on it.

**Comment by brandonwardell20** [comment]
Alright, I have safely shared the creds via proofpoint secure share. Let me know what your IP is and I will add it so you can access it.

Make sure to keep them safe so my DB doesn't get hacked and rack up a huge bill for me to pay. :)

**Comment by Tycodra** [comment]
The tables have now been added. Should I mark this issue as completed?

**Comment by brandonwardell20** [comment]
Yes!
